In [1]:
import numpy as np

In [2]:
#Random Array Generation

In [10]:
np.random.randint(1,10, size= (300,5))

array([[2, 7, 3, 7, 7],
       [5, 2, 1, 1, 3],
       [2, 4, 3, 2, 7],
       ...,
       [7, 7, 7, 5, 9],
       [5, 8, 5, 3, 6],
       [4, 5, 8, 6, 8]])

In [12]:
np.random.rand(4,4)

array([[0.74024063, 0.41783799, 0.73548385, 0.64751498],
       [0.84209435, 0.59984142, 0.87348391, 0.58233692],
       [0.06991929, 0.92663918, 0.44468435, 0.28246127],
       [0.10126809, 0.81597949, 0.81849293, 0.92946429]])

In [16]:
np.random.random((2,4))

array([[0.16061301, 0.46707805, 0.43984088, 0.90580535],
       [0.42876979, 0.16674432, 0.59763785, 0.93642342]])

In [18]:
np.random.randn(3,4)

array([[-0.02564505,  1.84934881, -0.27546158, -0.5778158 ],
       [-0.01717509,  0.68541217,  1.02374841, -2.05594013],
       [ 2.03458683,  1.12398474, -1.14427011, -1.03620017]])

In [19]:
np.random.normal(1,4, (3,3))   #mean = 0, std = 1

array([[-3.07631701,  1.43640604, -5.86412031],
       [-3.93842628, -0.10956673,  6.63842875],
       [ 2.83111238, -3.23447041,  1.84618145]])

In [23]:
np.random.seed(30)
np.random.random()

0.644143536068335

In [27]:
np.random.random()

0.9626078136743187

In [28]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr3 = np.array([[9, 10], [11, 12]])

In [29]:
arr1

array([[1, 2],
       [3, 4]])

In [30]:
arr2

array([[5, 6],
       [7, 8]])

In [31]:
arr3

array([[ 9, 10],
       [11, 12]])

In [32]:
np.vstack((arr1, arr2))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [33]:
np.hstack((arr1, arr2))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [34]:
np.concatenate((arr1, arr2), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [35]:
np.concatenate((arr1, arr2), axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [37]:
arr = np.random.choice([10, 20, 30, 40, 50], size=40)
print(arr)

[20 40 30 30 50 50 50 10 40 10 40 50 30 20 50 20 30 40 20 10 40 50 40 20
 20 20 10 50 10 20 10 20 30 30 40 40 20 50 50 30]


In [38]:
arr = np.random.uniform(5, 10, size=(2, 3))
print(arr)

[[6.06040416 6.33646584 6.86947039]
 [7.86544253 9.58679039 9.09487968]]


In [39]:
arr = np.random.permutation(10)
print(arr)

[0 6 5 1 3 7 8 2 4 9]


In [40]:
arr = np.array([1, 2, 3, 4, 5])
np.random.shuffle(arr)
print(arr)

[2 3 5 4 1]


In [41]:
arr = np.random.sample((2, 3))
print(arr)

[[0.61230216 0.31101022 0.32492247]
 [0.78300166 0.91315956 0.87141294]]


In [53]:
np.random.seed(45)
np.random.random()

0.9890115134756001

In [69]:
np.random.RandomState(50)
np.random.random()

0.2826672065311674