In [ ]:
!pip install numpy

In [1]:
import numpy as np

## Why NuMpy?

- Mathematical and logical operations on **arrays**.

- Efficient storage and manipulation of **numerical arrays** is which is fundamental in  the process of  **data science**.

- NumPy arrays form the core of nearly the entire **ecosystem** of **data science** tools in Python,

In [2]:
import time as tm

size_1 = 1000000

def pure_python_version():
    start_time_pp =  tm.time() ## time of start of code execution
    list1 = range(size_1)
    list2 = range(size_1)
    sum_list=[list1[i]+list2[i] for i in range(len(list1))]
    end_time_pp =  tm.time()
    return end_time_pp - start_time_pp ## end time for execution (difference)

def numpy_version():
    start_time_np = tm.time()
    array1 = np.arange(size_1)
    array2 =  np.arange(size_1)
    sum_array = array1 + array2
    end_time_np = tm.time()
    return end_time_np - start_time_np ## end time for execution (difference)

python_time = pure_python_version()
numpy_time  = numpy_version()

print("pure python version=",python_time)
print("numpy =",numpy_time)

pure python version= 0.3496744632720947
numpy = 0.009819746017456055


In [3]:
my_list=[2,3,4,6,7,8]

In [4]:
type(my_list)

list

In [6]:
ar = np.array(my_list)

In [7]:
type(ar)

numpy.ndarray

In [8]:
ar

array([2, 3, 4, 6, 7, 8])

In [9]:
ar.ndim

1

In [10]:
array_2 = [[1,2,3],[4,5,6],[7,8,9]]
array_3= np.array(array_2)
array_3
type(array_3)

numpy.ndarray

In [11]:
array_3.ndim

2

In [12]:
array_3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
array_3.size

9

In [14]:
array_3.shape

(3, 3)

In [15]:
a = np.array([1, 2, 3,7,5,1], ndmin = 2) 
print (a)
np.ndim(a)

[[1 2 3 7 5 1]]


2

In [16]:
a = np.array([1, 2, 3,7,5,1], ndmin = 10) 
print (a)
np.ndim(a)

[[[[[[[[[[1 2 3 7 5 1]]]]]]]]]]


10

In [17]:
a = np.array([1, 2, 3, 4], dtype = complex) 
print (a)

[1.+0.j 2.+0.j 3.+0.j 4.+0.j]


In [18]:
array_3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
array_3[2]

array([7, 8, 9])

In [20]:
array_3[0]

array([1, 2, 3])

In [23]:
array_3[1,1]

5

In [24]:
array_3[0,0]

1

In [25]:
array_3[0:2,1:3]

array([[2, 3],
       [5, 6]])

In [26]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [28]:
np.arange(5,15, 2)

array([ 5,  7,  9, 11, 13])

In [30]:
np.arange(5, -10, -1)

array([ 5,  4,  3,  2,  1,  0, -1, -2, -3, -4, -5, -6, -7, -8, -9])

In [35]:
np.zeros((3,5), dtype = int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [36]:
np.ones((3,3), dtype= int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [41]:
np.eye(6,6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [46]:
np.linspace(1,10, 5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [49]:
np.linspace(-10,10, 30)

array([-10.        ,  -9.31034483,  -8.62068966,  -7.93103448,
        -7.24137931,  -6.55172414,  -5.86206897,  -5.17241379,
        -4.48275862,  -3.79310345,  -3.10344828,  -2.4137931 ,
        -1.72413793,  -1.03448276,  -0.34482759,   0.34482759,
         1.03448276,   1.72413793,   2.4137931 ,   3.10344828,
         3.79310345,   4.48275862,   5.17241379,   5.86206897,
         6.55172414,   7.24137931,   7.93103448,   8.62068966,
         9.31034483,  10.        ])

In [50]:
array_3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [52]:
array_3.reshape(1,9)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [53]:
array_3.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [54]:
x=[[1,2,3,4],[4,5,6,7],[7,8,9,10],[10,11,12,13]]
x=np.array(x)
x

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  7],
       [ 7,  8,  9, 10],
       [10, 11, 12, 13]])

In [55]:
x.reshape(2,8)

array([[ 1,  2,  3,  4,  4,  5,  6,  7],
       [ 7,  8,  9, 10, 10, 11, 12, 13]])

In [56]:
x.reshape(8,2)

array([[ 1,  2],
       [ 3,  4],
       [ 4,  5],
       [ 6,  7],
       [ 7,  8],
       [ 9, 10],
       [10, 11],
       [12, 13]])

In [57]:
x

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  7],
       [ 7,  8,  9, 10],
       [10, 11, 12, 13]])

In [58]:
x.min()

1

In [59]:
x.max()

13

In [60]:
x.argmax()

15

In [61]:
x.argmin()

0

In [62]:
x.sum()

112

In [63]:
x.mean()

7.0

In [65]:
x.std()

3.5355339059327378

In [66]:
x.var()

12.5

In [68]:
x.min(axis = 0)

array([1, 2, 3, 4])

In [69]:
x.min(axis = 1)

array([ 1,  4,  7, 10])

In [70]:
x

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  7],
       [ 7,  8,  9, 10],
       [10, 11, 12, 13]])

In [72]:
x.max(axis=1)

array([ 4,  7, 10, 13])

In [73]:
np.array([1,2,3,4], ndmin=4)

array([[[[1, 2, 3, 4]]]])

In [75]:
x.flatten()

array([ 1,  2,  3,  4,  4,  5,  6,  7,  7,  8,  9, 10, 10, 11, 12, 13])

In [77]:
x.transpose()

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12],
       [ 4,  7, 10, 13]])

In [78]:
x

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  7],
       [ 7,  8,  9, 10],
       [10, 11, 12, 13]])

In [81]:
A = np.array([ [4, 10, 11], [21, 22, 23], [31, 32, 33] ])
B = np.ones((3,3))
C = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(A)

[[ 4 10 11]
 [21 22 23]
 [31 32 33]]


In [80]:
B

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [82]:
C

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [83]:
A + B

array([[ 5., 11., 12.],
       [22., 23., 24.],
       [32., 33., 34.]])

In [84]:
A-B

array([[ 3.,  9., 10.],
       [20., 21., 22.],
       [30., 31., 32.]])

In [85]:
A*C

array([[  4,  20,  33],
       [ 84, 110, 138],
       [217, 256, 297]])

In [86]:
A/C

array([[4.        , 5.        , 3.66666667],
       [5.25      , 4.4       , 3.83333333],
       [4.42857143, 4.        , 3.66666667]])

In [87]:
A%C

array([[0, 0, 2],
       [1, 2, 5],
       [3, 0, 6]])

In [88]:
A//C

array([[4, 5, 3],
       [5, 4, 3],
       [4, 4, 3]])

In [89]:
A**2

array([[  16,  100,  121],
       [ 441,  484,  529],
       [ 961, 1024, 1089]])

In [90]:
np.sqrt(A)

array([[2.        , 3.16227766, 3.31662479],
       [4.58257569, 4.69041576, 4.79583152],
       [5.56776436, 5.65685425, 5.74456265]])

In [92]:
np.dot(A,B)

array([[25., 25., 25.],
       [66., 66., 66.],
       [96., 96., 96.]])

In [93]:
A

array([[ 4, 10, 11],
       [21, 22, 23],
       [31, 32, 33]])

In [94]:
B

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [95]:
np.dot(A,C)

array([[121, 146, 171],
       [270, 336, 402],
       [390, 486, 582]])

In [96]:
A

array([[ 4, 10, 11],
       [21, 22, 23],
       [31, 32, 33]])

In [97]:
C

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [98]:
np.exp(A)

array([[5.45981500e+01, 2.20264658e+04, 5.98741417e+04],
       [1.31881573e+09, 3.58491285e+09, 9.74480345e+09],
       [2.90488497e+13, 7.89629602e+13, 2.14643580e+14]])

In [99]:
np.log(A)

array([[1.38629436, 2.30258509, 2.39789527],
       [3.04452244, 3.09104245, 3.13549422],
       [3.4339872 , 3.4657359 , 3.49650756]])

In [100]:
a=np.array([[11.667,23.662],[33.21,45.887]])

In [101]:
a

array([[11.667, 23.662],
       [33.21 , 45.887]])

In [103]:
np.around(a, decimals=1)

array([[11.7, 23.7],
       [33.2, 45.9]])

In [104]:
x

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  7],
       [ 7,  8,  9, 10],
       [10, 11, 12, 13]])

In [105]:
x.sum(axis=0)

array([22, 26, 30, 34])

In [106]:
x.sum(axis=1)

array([10, 22, 34, 46])

In [111]:
np.concatenate([A,B,C])

array([[ 4., 10., 11.],
       [21., 22., 23.],
       [31., 32., 33.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.]])